class AppString {
  static const String cooksy = "Cooksy",
      allTheResipes = "All the recipes\n on your fingertips",
      at = "Ⓡ ",
      cookingOn = "Cooking on Thermomix",
      madeEasy = "made easy",
      letsStart = "Let's start",
      inspiration = "Inspiration",
      recipes = "My recipes",
      settings = "Settings",
      recipe = "Recipe\n",
      ofTheDay = "of the day",
      cook = "Cook\n",
      likrPro = 'like pro',
      check = "Check\n",
      newUpdates = "new updates",
      reneRedzwpi = "René Redzepi\n",
      recommendsYou = "recommends you",
      myRecipes = "My recipes",
      showIngredients = "Show Ingredients",
      letsCook = "Let's Cook",
      cansel = "Cansel";
}
